-- MySQL Script generated by MySQL Workbench
-- 10/18/15 20:17:37
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema iloveshawa
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `iloveshawa` ;

-- -----------------------------------------------------
-- Schema iloveshawa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `iloveshawa` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `iloveshawa` ;

-- -----------------------------------------------------
-- Table `iloveshawa`.`ShawaShop`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `iloveshawa`.`ShawaShop` ;

CREATE TABLE IF NOT EXISTS `iloveshawa`.`ShawaShop` (
  `id` INT NOT NULL COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  `coordinates` VARCHAR(100) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iloveshawa`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `iloveshawa`.`User` ;

CREATE TABLE IF NOT EXISTS `iloveshawa`.`User` (
  `id` INT NOT NULL COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  `image_url` VARCHAR(45) NULL COMMENT '',
  `email` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `email_UNIQUE` (`email` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iloveshawa`.`Review`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `iloveshawa`.`Review` ;

CREATE TABLE IF NOT EXISTS `iloveshawa`.`Review` (
  `id` INT NOT NULL COMMENT '',
  `text` LONGTEXT NOT NULL COMMENT '',
  `positive` TINYINT(1) NOT NULL COMMENT '',
  `user_id` INT NOT NULL COMMENT '',
  `shop_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_review_user1_idx` (`user_id` ASC)  COMMENT '',
  INDEX `fk_review_shawarma_shop1_idx` (`shop_id` ASC)  COMMENT '',
  CONSTRAINT `fk_review_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `iloveshawa`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_review_shawarma_shop1`
    FOREIGN KEY (`shop_id`)
    REFERENCES `iloveshawa`.`ShawaShop` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iloveshawa`.`Image`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `iloveshawa`.`Image` ;

CREATE TABLE IF NOT EXISTS `iloveshawa`.`Image` (
  `id` INT NOT NULL COMMENT '',
  `url` VARCHAR(45) NOT NULL COMMENT '',
  `shop_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_image_shawarma_shop1_idx` (`shop_id` ASC)  COMMENT '',
  CONSTRAINT `fk_image_shawarma_shop1`
    FOREIGN KEY (`shop_id`)
    REFERENCES `iloveshawa`.`ShawaShop` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iloveshawa`.`Score`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `iloveshawa`.`Score` ;

CREATE TABLE IF NOT EXISTS `iloveshawa`.`Score` (
  `id` INT NOT NULL COMMENT '',
  `value` INT NOT NULL COMMENT '',
  `user_id` INT NOT NULL COMMENT '',
  `shop_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_score_user1_idx` (`user_id` ASC)  COMMENT '',
  INDEX `fk_score_shawarma_shop1_idx` (`shop_id` ASC)  COMMENT '',
  CONSTRAINT `fk_score_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `iloveshawa`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_score_shawarma_shop1`
    FOREIGN KEY (`shop_id`)
    REFERENCES `iloveshawa`.`ShawaShop` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iloveshawa`.`Like`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `iloveshawa`.`Like` ;

CREATE TABLE IF NOT EXISTS `iloveshawa`.`Like` (
  `id` INT NOT NULL COMMENT '',
  `user_id` INT NOT NULL COMMENT '',
  `review_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_like_user1_idx` (`user_id` ASC)  COMMENT '',
  INDEX `fk_like_review1_idx` (`review_id` ASC)  COMMENT '',
  CONSTRAINT `fk_like_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `iloveshawa`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_like_review1`
    FOREIGN KEY (`review_id`)
    REFERENCES `iloveshawa`.`Review` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
