

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ILoveShawa.Domain
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class Entities : DbContext
{
    public Entities()
        : base("name=Entities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<image> image { get; set; }

    public virtual DbSet<like> like { get; set; }

    public virtual DbSet<review> review { get; set; }

    public virtual DbSet<score> score { get; set; }

    public virtual DbSet<shawarma_shop> shawarma_shop { get; set; }

    public virtual DbSet<user> user { get; set; }

}

}

