

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ILoveShawa.Domain
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class ILoveShawaContainer : DbContext
{
    public ILoveShawaContainer()
        : base("name=Entities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<image> images { get; set; }

    public virtual DbSet<like> likes { get; set; }

    public virtual DbSet<review> reviews { get; set; }

    public virtual DbSet<score> scores { get; set; }

    public virtual DbSet<shawashop> shawashops { get; set; }

    public virtual DbSet<user> users { get; set; }

}

}

