-- MySQL Script generated by MySQL Workbench
-- 10/18/15 17:17:41
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema iloveshawa
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `iloveshawa` ;

-- -----------------------------------------------------
-- Schema iloveshawa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `iloveshawa` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `iloveshawa` ;

-- -----------------------------------------------------
-- Table `iloveshawa`.`shawa_shop`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `iloveshawa`.`shawa_shop` ;

CREATE TABLE IF NOT EXISTS `iloveshawa`.`shawa_shop` (
  `id` INT NOT NULL COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  `coordinates` POINT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iloveshawa`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `iloveshawa`.`user` ;

CREATE TABLE IF NOT EXISTS `iloveshawa`.`user` (
  `id` INT NOT NULL COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  `image_url` VARCHAR(45) NOT NULL COMMENT '',
  `email` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iloveshawa`.`review`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `iloveshawa`.`review` ;

CREATE TABLE IF NOT EXISTS `iloveshawa`.`review` (
  `id` INT NOT NULL COMMENT '',
  `text` TEXT NOT NULL COMMENT '',
  `positive` TINYINT(1) NOT NULL COMMENT '',
  `user_id` INT NOT NULL COMMENT '',
  `shop_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`, `user_id`, `shop_id`)  COMMENT '',
  INDEX `fk_review_user1_idx` (`user_id` ASC)  COMMENT '',
  INDEX `fk_review_shawarma_shop1_idx` (`shop_id` ASC)  COMMENT '',
  CONSTRAINT `fk_review_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `iloveshawa`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_review_shawarma_shop1`
    FOREIGN KEY (`shop_id`)
    REFERENCES `iloveshawa`.`shawa_shop` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iloveshawa`.`image`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `iloveshawa`.`image` ;

CREATE TABLE IF NOT EXISTS `iloveshawa`.`image` (
  `id` INT NOT NULL COMMENT '',
  `url` VARCHAR(45) NULL COMMENT '',
  `shop_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`, `shop_id`)  COMMENT '',
  INDEX `fk_image_shawarma_shop1_idx` (`shop_id` ASC)  COMMENT '',
  CONSTRAINT `fk_image_shawarma_shop1`
    FOREIGN KEY (`shop_id`)
    REFERENCES `iloveshawa`.`shawa_shop` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iloveshawa`.`score`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `iloveshawa`.`score` ;

CREATE TABLE IF NOT EXISTS `iloveshawa`.`score` (
  `id` INT NOT NULL COMMENT '',
  `value` INT NOT NULL COMMENT '',
  `user_id` INT NULL COMMENT '',
  `shop_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`, `user_id`, `shop_id`)  COMMENT '',
  INDEX `fk_score_user1_idx` (`user_id` ASC)  COMMENT '',
  INDEX `fk_score_shawarma_shop1_idx` (`shop_id` ASC)  COMMENT '',
  CONSTRAINT `fk_score_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `iloveshawa`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_score_shawarma_shop1`
    FOREIGN KEY (`shop_id`)
    REFERENCES `iloveshawa`.`shawa_shop` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iloveshawa`.`like`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `iloveshawa`.`like` ;

CREATE TABLE IF NOT EXISTS `iloveshawa`.`like` (
  `id` INT NOT NULL COMMENT '',
  `user_id` INT NOT NULL COMMENT '',
  `review_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`, `user_id`, `review_id`)  COMMENT '',
  INDEX `fk_like_user1_idx` (`user_id` ASC)  COMMENT '',
  INDEX `fk_like_review1_idx` (`review_id` ASC)  COMMENT '',
  CONSTRAINT `fk_like_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `iloveshawa`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_like_review1`
    FOREIGN KEY (`review_id`)
    REFERENCES `iloveshawa`.`review` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
