//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ILoveShawa.Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ILoveShawaContainer : DbContext
    {
        public ILoveShawaContainer()
            : base("name=ILoveShawaContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Image> Images { get; set; }
        public virtual DbSet<Like> Likes { get; set; }
        public virtual DbSet<Review> Reviews { get; set; }
        public virtual DbSet<Score> Scores { get; set; }
        public virtual DbSet<ShawaShop> ShawaShops { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
