
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ILoveShawa.Domain
{

using System;
    using System.Collections.Generic;
    
public partial class Like
{

    public int id { get; set; }

    public int user_id { get; set; }

    public int review_id { get; set; }



    public virtual Review review { get; set; }

    public virtual User user { get; set; }

}

}
