
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ILoveShawa.Domain
{

using System;
    using System.Collections.Generic;
    
public partial class score
{

    public int id { get; set; }

    public int value { get; set; }

    public int user_id { get; set; }

    public int shop_id { get; set; }



    public virtual shawarma_shop shawarma_shop { get; set; }

    public virtual user user { get; set; }

}

}
