//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ILoveShawa.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Score
    {
        public int id { get; set; }
        public int value { get; set; }
        public int user_id { get; set; }
        public int shop_id { get; set; }
    
        public virtual ShawaShop shawashop { get; set; }
        public virtual User user { get; set; }
    }
}
